/**
 * bootstrap — Self-contained project initialization
 *
 * Replaces the external starter-kit's init-project.mjs.
 * Generates project structure using ai-rules core/ assets directly.
 * Zero external dependencies — Node.js built-in modules only.
 */

import {
  copyFileSync, existsSync, mkdirSync,
  readFileSync, readdirSync, writeFileSync,
} from 'fs'
import { join } from 'path'

// ── Stack Presets ───────────────────────────────────────────────────────────

const STACKS = {
  frontend: {
    react:  { label: 'React + TypeScript + Vite' },
    next:   { label: 'Next.js 14+ (App Router)' },
    vue:    { label: 'Vue 3 + TypeScript + Vite' },
  },
  backend: {
    fastapi: { label: 'FastAPI + Python 3.11' },
    express: { label: 'Express + TypeScript' },
    django:  { label: 'Django + DRF' },
    none:    { label: 'None (Frontend only)' },
  },
  database: {
    postgres: { label: 'PostgreSQL 15+' },
    mysql:    { label: 'MySQL 8.0+' },
    mongodb:  { label: 'MongoDB' },
    none:     { label: 'None' },
  },
}

const PRESETS = {
  'react-fastapi-postgres': { frontend: 'react', backend: 'fastapi', database: 'postgres' },
  'next-fastapi-postgres':  { frontend: 'next',  backend: 'fastapi', database: 'postgres' },
  'react-express-postgres': { frontend: 'react', backend: 'express', database: 'postgres' },
  'react-express-mongodb':  { frontend: 'react', backend: 'express', database: 'mongodb' },
  'next-none-none':         { frontend: 'next',  backend: 'none',    database: 'none' },
}

// ── Main Entry ──────────────────────────────────────────────────────────────

/**
 * @param {object} options
 * @param {string} options.projectDir  Absolute path to the new project directory
 * @param {string} options.name        Project name (kebab-case)
 * @param {string} options.stack       Preset stack key (e.g. 'react-fastapi-postgres')
 * @param {string} options.aiRulesRoot Absolute path to the ai-rules repository root
 * @returns {string[]} log messages
 */
export async function bootstrapProject({ projectDir, name, stack, aiRulesRoot }) {
  const log = []
  const preset = PRESETS[stack]
  if (!preset) {
    throw new Error(
      `Unknown stack preset: "${stack}". Available: ${Object.keys(PRESETS).join(', ')}`
    )
  }

  // Create project root
  mkdirSync(projectDir, { recursive: true })

  // 1. CLAUDE.md — compose from core/rules/*.md
  log.push(writeClaudeMd(projectDir, name, preset, aiRulesRoot))

  // 2. INTENT.md
  log.push(writeFile(projectDir, 'INTENT.md', generateIntentMd(name)))

  // 3. SESSION.md
  log.push(writeFile(projectDir, 'SESSION.md', generateSessionMd(name)))

  // 4. FAILURE_LOG.md
  log.push(writeFile(projectDir, 'FAILURE_LOG.md', generateFailureLogMd(name)))

  // 5. .env.example
  log.push(writeFile(projectDir, '.env.example', generateEnvExample(name, preset)))

  // 6. .gitignore
  log.push(writeFile(projectDir, '.gitignore', generateGitignore(preset)))

  // 7. .claude/settings.local.json
  const settingsDir = join(projectDir, '.claude')
  mkdirSync(settingsDir, { recursive: true })
  log.push(writeFile(
    projectDir,
    '.claude/settings.local.json',
    JSON.stringify(generateSettingsLocal(preset), null, 2) + '\n',
  ))

  // 8. .claude/agents/*.md — copy from core/agents/
  log.push(...copyAgents(projectDir, aiRulesRoot))

  // 9. docs/00_INDEX.md
  mkdirSync(join(projectDir, 'docs'), { recursive: true })
  log.push(writeFile(projectDir, 'docs/00_INDEX.md', generateDocsIndex(name, preset)))

  log.push(`\n  Project bootstrapped: ${projectDir}`)
  return log
}

// ── CLAUDE.md ────────────────────────────────────────────────────────────────

function writeClaudeMd(projectDir, name, preset, aiRulesRoot) {
  const rulesDir = join(aiRulesRoot, 'core', 'rules')
  const ruleFiles = readdirSync(rulesDir)
    .filter(f => f.endsWith('.md'))
    .sort()

  const frontendLabel = STACKS.frontend[preset.frontend]?.label ?? preset.frontend
  const backendLabel = STACKS.backend[preset.backend]?.label ?? preset.backend
  const dbLabel = STACKS.database[preset.database]?.label ?? preset.database

  const header = [
    `# CLAUDE.md — ${name}`,
    '',
    `> Generated by [ai-rules](https://github.com/gencrewai/ai-rules) scaffold`,
    `> Date: ${todayISO()}`,
    `> Stack: ${frontendLabel} + ${backendLabel} + ${dbLabel}`,
    '',
    '<!-- ai-rules:keep — Custom rules below this line are preserved on re-sync -->',
    '',
  ].join('\n')

  const sections = ruleFiles.map(f => {
    const content = readFileSync(join(rulesDir, f), 'utf-8')
    return content.trim()
  })

  const fullContent = header + sections.join('\n\n---\n\n') + '\n'
  writeFileSync(join(projectDir, 'CLAUDE.md'), fullContent, 'utf-8')
  return '  CREATE: CLAUDE.md (composed from core/rules/)'
}

// ── INTENT.md ────────────────────────────────────────────────────────────────

function generateIntentMd(name) {
  return `---
context:
  docs: []       # planner fills — docs for builder to read
  touch: []      # planner fills — files expected to be created/modified
  agents: [builder, reviewer]
---

# INTENT.md — ${name}

> Current task goal. Updated by planner at each task start.
> Builder reads only context.docs and starts implementation (no full-repo scan).

## Goal

_Start with the planner agent to fill this section._

## Scope

### Include
-

### Exclude
-

## Success Criteria
- [ ]

## Tasks
- [ ] 1.
`
}

// ── SESSION.md ───────────────────────────────────────────────────────────────

function generateSessionMd(name) {
  return `# SESSION.md — ${name}

---HANDOFF---
date: ${todayISO()}
branch: main
agent: ai-rules-scaffold
status: complete
done:
  - Project initialized (ai-rules scaffold)
next:
  - Write INTENT.md and invoke planner agent
blocked:
files_touched:
  - CLAUDE.md (project rules)
  - INTENT.md (initial template)
  - docs/00_INDEX.md (document map)
verify_cmd:
first_action: "git status && cat INTENT.md"
handoff_provenance: agent
---END---
`
}

// ── FAILURE_LOG.md ───────────────────────────────────────────────────────────

function generateFailureLogMd(name) {
  return `# FAILURE_LOG.md — ${name}

> Recurring failure patterns are recorded here.
> Planner checks this file at session start.
> Builder records patterns here after 3 consecutive failures.

## Format

\`\`\`
## FAIL-{N}
- Symptom: {what error/problem}
- Tried: {what was attempted}
- Cause: {why it failed}
- Fix: {how it was resolved}
- Prevention: {what to check first next time}
\`\`\`

---

_No entries yet. Builder will add the first failure pattern here._
`
}

// ── .env.example ─────────────────────────────────────────────────────────────

function generateEnvExample(name, preset) {
  const dbName = name.replace(/-/g, '_')
  const lines = [
    '# .env.example — Copy to .env and fill in real values',
    `# Project: ${name}`,
    '',
  ]

  // Database
  if (preset.database === 'postgres') {
    lines.push('# Database')
    lines.push(`DATABASE_URL=postgresql://postgres:postgres@localhost:5432/${dbName}`)
    lines.push('')
  } else if (preset.database === 'mysql') {
    lines.push('# Database')
    lines.push(`DATABASE_URL=mysql://root:password@localhost:3306/${dbName}`)
    lines.push('')
  } else if (preset.database === 'mongodb') {
    lines.push('# Database')
    lines.push(`MONGODB_URL=mongodb://localhost:27017/${dbName}`)
    lines.push('')
  }

  // Backend auth
  if (preset.backend === 'fastapi') {
    lines.push('# Auth (FastAPI)')
    lines.push('SECRET_KEY=your-secret-key-minimum-32-characters')
    lines.push('ALGORITHM=HS256')
    lines.push('ACCESS_TOKEN_EXPIRE_MINUTES=15')
    lines.push('REFRESH_TOKEN_EXPIRE_DAYS=7')
    lines.push('')
  } else if (preset.backend === 'express') {
    lines.push('# Auth (Express)')
    lines.push('JWT_SECRET=your-secret-key-minimum-32-characters')
    lines.push('JWT_EXPIRES_IN=15m')
    lines.push('')
  }

  // Frontend
  if (preset.frontend !== 'none') {
    const prefix = preset.frontend === 'next' ? 'NEXT_PUBLIC' : 'VITE'
    lines.push('# Frontend')
    lines.push(`${prefix}_API_URL=http://localhost:8000/api/v1`)
    lines.push('')
  }

  lines.push('# Payment (if needed)')
  lines.push('# STRIPE_SECRET_KEY=sk_test_...')
  lines.push('# STRIPE_WEBHOOK_SECRET=whsec_...')
  lines.push('')
  lines.push('# Production')
  lines.push('# ALLOWED_ORIGINS=https://myapp.com')
  lines.push('# SENTRY_DSN=')

  return lines.join('\n') + '\n'
}

// ── .gitignore ───────────────────────────────────────────────────────────────

function generateGitignore(preset) {
  const lines = [
    '# Dependencies',
    'node_modules/',
    '__pycache__/',
    '.venv/',
    '',
    '# Environment — never commit',
    '.env',
    '.env.local',
    '.env.*.local',
    '!.env.example',
    '',
    '# Build output',
    'dist/',
    'build/',
    '.next/',
    '',
    '# IDE',
    '.vscode/',
    '.idea/',
    '*.swp',
    '',
    '# OS',
    '.DS_Store',
    'Thumbs.db',
    '',
    '# DB dumps',
    '*.sql',
    '*.dump',
    'backup_*.sql',
    '',
    '# Prisma',
    '.prisma/',
    '',
    '# AI logs raw exports',
    'ai_logs/done/',
  ]

  return lines.join('\n') + '\n'
}

// ── .claude/settings.local.json ──────────────────────────────────────────────

function generateSettingsLocal(preset) {
  const allow = [
    // Read tools
    'Read', 'Edit', 'Write',
    // Git (safe subset)
    'Bash(git status*)', 'Bash(git log*)', 'Bash(git diff*)',
    'Bash(git fetch*)', 'Bash(git branch*)', 'Bash(git checkout -b *)',
    'Bash(git add*)', 'Bash(git commit*)', 'Bash(git push origin *)',
    'Bash(git stash*)', 'Bash(git rev-list*)',
    // Node/NPM
    'Bash(node *)', 'Bash(npm *)', 'Bash(npx *)',
    // Utilities
    'Bash(ls *)', 'Bash(cat *)', 'Bash(head *)', 'Bash(tail *)',
    'Bash(find *)', 'Bash(grep *)', 'Bash(echo *)', 'Bash(cp *)',
    'Bash(mkdir *)', 'Bash(tree *)', 'Bash(wc *)', 'Bash(curl *)',
    // GitHub CLI
    'Bash(gh *)',
    // Web
    'WebFetch(domain:*)',
  ]

  // Stack-specific permissions
  if (preset.backend === 'fastapi') {
    allow.push('Bash(python *)', 'Bash(pip *)', 'Bash(ruff *)', 'Bash(alembic *)')
  } else if (preset.backend === 'express') {
    allow.push('Bash(tsc *)')
  } else if (preset.backend === 'django') {
    allow.push('Bash(python *)', 'Bash(pip *)')
  }

  if (preset.database === 'postgres' || preset.database === 'mysql') {
    allow.push('Bash(docker *)', 'Bash(docker-compose *)')
  }

  return { permissions: { allow } }
}

// ── Agent files ──────────────────────────────────────────────────────────────

function copyAgents(projectDir, aiRulesRoot) {
  const log = []
  const srcDir = join(aiRulesRoot, 'core', 'agents')
  const dstDir = join(projectDir, '.claude', 'agents')
  mkdirSync(dstDir, { recursive: true })

  const files = readdirSync(srcDir).filter(f => f.endsWith('.md'))
  for (const f of files) {
    copyFileSync(join(srcDir, f), join(dstDir, f))
    log.push(`  COPY: .claude/agents/${f}`)
  }
  return log
}

// ── docs/00_INDEX.md ─────────────────────────────────────────────────────────

function generateDocsIndex(name, preset) {
  const frontendLabel = STACKS.frontend[preset.frontend]?.label ?? preset.frontend
  const backendLabel = STACKS.backend[preset.backend]?.label ?? preset.backend
  const dbLabel = STACKS.database[preset.database]?.label ?? preset.database

  return `# docs/00_INDEX.md — ${name}

> Generated: ${todayISO()} | Stack: ${frontendLabel} + ${backendLabel} + ${dbLabel}

## Document Priority

\`\`\`
1. INTENT.md          — Current task goal (highest priority)
2. CLAUDE.md          — AI behavior rules
3. docs/00_INDEX.md   — This file (document map)
4. Role-specific docs — Reference
5. Existing code      — Legacy / conventions
\`\`\`

## Session Management

- **Session start**: Check SESSION.md HANDOFF block -> Check INTENT.md -> git status
- **Session end**: Update SESSION.md HANDOFF block (mandatory)
- **Context limit** (~30 turns): Snapshot to SESSION.md, request new session
`
}

// ── Utilities ────────────────────────────────────────────────────────────────

function todayISO() {
  return new Date().toISOString().split('T')[0]
}

function writeFile(projectDir, relativePath, content) {
  const fullPath = join(projectDir, relativePath)
  const dir = join(projectDir, ...relativePath.split('/').slice(0, -1))
  if (dir !== projectDir) mkdirSync(dir, { recursive: true })
  writeFileSync(fullPath, content, 'utf-8')
  return `  CREATE: ${relativePath}`
}
