/**
 * antigravity.mjs — Google Antigravity adapter.
 *
 * Antigravity runs on the Gemini 3 backend but ships with its own local
 * directory convention:
 *
 *   - Local project:   `.agent/agents/*.md`, rules file `AGENTS.md`
 *   - Global (user):   `~/.gemini/antigravity/`
 *
 * Because the model is Gemini, call-site directives that target Claude's
 * `Task` tool don't apply. We reuse the Gemini path-rewrite table for
 * references to `CLAUDE.md` / `.claude/` and only override the directory
 * names that Antigravity has chosen to differ from stock Gemini.
 */

import { neutralizeClaudeDirectives, rewritePaths } from '../lib/agent-transform.mjs'

function transform(content) {
  // Start from the Gemini mapping (CLAUDE.md → GEMINI.md etc.),
  // then retarget the directories that Antigravity owns.
  let out = neutralizeClaudeDirectives(rewritePaths(content, 'gemini'))
  out = out
    .replace(/\.gemini\/agents\//g, '.agent/agents/')
    .replace(/\bGEMINI\.md\b/g, 'AGENTS.md')
  return out
}

export function generate(blocks, toolConfig, profile) {
  const timestamp = new Date().toISOString()
  const header = [
    `# AGENTS.md — ${profile.project} (Antigravity)`,
    ``,
    `<!-- Generated by ai-rules | ${timestamp} | Profile: ${profile.project} -->`,
    `<!-- Antigravity runs on Gemini 3 backend; role docs live under .agent/agents/ -->`,
    ``,
  ].join('\n')

  const body = blocks.map(transform).join('\n\n---\n\n')
  return [{
    path: toolConfig.output || 'AGENTS.md',
    content: header + body,
  }]
}

export function generateAgents(agents, toolConfig, profile) {
  if (!agents?.length) return []
  if (toolConfig?.agents?.enabled === false) return []
  const outputDir = toolConfig?.agents?.output || '.agent/agents/'
  const normalizedDir = outputDir.replace(/\/?$/, '/')
  const timestamp = new Date().toISOString()

  return agents.map(a => {
    const desc = String(a.frontmatter?.description || '').replace(/\s+/g, ' ').trim()
    const tools = Array.isArray(a.frontmatter?.tools)
      ? a.frontmatter.tools.join(', ')
      : (a.frontmatter?.tools || '')
    const body = transform(a.body)
    const header = [
      `# Agent: ${a.name}`,
      `<!-- Generated by ai-rules | ${timestamp} | Profile: ${profile.project} -->`,
      `<!-- Source: core/agents/${a.name}.md — edit there, not here -->`,
      desc ? `\n> ${desc}` : '',
      tools ? `> Reference tools: ${tools}` : '',
      ``,
    ].filter(Boolean).join('\n')
    return {
      path: `${normalizedDir}${a.name}.md`,
      content: header + '\n' + body,
    }
  })
}
