/**
 * cline.mjs — Cline adapter.
 *
 * Cline reads `.clinerules` at the project root. It has no native subagent
 * runner but recognizes role prompts placed under `.cline/agents/` as
 * reusable context.
 *
 * Strategy:
 *   - Rules → `.clinerules` (concatenated blocks with path rewriting).
 *   - Agents → `.cline/agents/{name}.md` (role prompts, paths rewritten,
 *     Claude-only directives neutralized).
 */

import { neutralizeClaudeDirectives, rewritePaths } from '../lib/agent-transform.mjs'

export function generate(blocks, toolConfig, profile) {
  const timestamp = new Date().toISOString()
  const header = [
    `# .clinerules — ${profile.project}`,
    `# Generated by ai-rules | ${timestamp} | Profile: ${profile.project}`,
    `# Edit in ai-rules/core/ or ai-rules/extensions/, not here.`,
    ``,
  ].join('\n')

  const body = blocks.map(b => neutralizeClaudeDirectives(rewritePaths(b, 'cline'))).join('\n\n---\n\n')

  return [{
    path: toolConfig.output || '.clinerules',
    content: header + body,
  }]
}

export function generateAgents(agents, toolConfig, profile) {
  if (!agents?.length) return []
  if (toolConfig?.agents?.enabled === false) return []
  const timestamp = new Date().toISOString()
  const outputDir = toolConfig?.agents?.output || '.cline/agents/'
  const normalizedDir = outputDir.replace(/\/?$/, '/')

  return agents.map(a => {
    const desc = String(a.frontmatter?.description || '').replace(/\s+/g, ' ').trim()
    const body = neutralizeClaudeDirectives(rewritePaths(a.body, 'cline'))
    const header = [
      `# Cline Role: ${a.name}`,
      `<!-- Generated by ai-rules | ${timestamp} | Profile: ${profile.project} -->`,
      `<!-- Source: core/agents/${a.name}.md -->`,
      desc ? `\n> ${desc}\n` : '',
    ].filter(Boolean).join('\n')
    return {
      path: `${normalizedDir}${a.name}.md`,
      content: header + '\n' + body,
    }
  })
}
