/**
 * codex.mjs — OpenAI Codex CLI adapter.
 *
 * Codex uses `AGENTS.md` at the project root as its instruction file and
 * supports native "agents" loaded from an `agents/` folder (configurable via
 * `~/.codex/config.toml`). This adapter emits the rules file as AGENTS.md and
 * mirrors each ai-rules agent to `.codex/agents/{name}.md` with path
 * references rewritten from Claude conventions.
 *
 * Note: automatic config.toml injection is deliberately out of scope for this
 * adapter (see Step 3 in the roadmap) — operators can point Codex at the
 * emitted `.codex/agents/` folder manually.
 */

import { rewritePaths } from '../lib/agent-transform.mjs'

export function generate(blocks, toolConfig, profile) {
  const timestamp = new Date().toISOString()
  const header = [
    `# AGENTS.md — ${profile.project} (Codex instructions)`,
    ``,
    `> ⚠️ Generated by [ai-rules](https://github.com/gencrewai/ai-rules). Edit in \`ai-rules/core/\` or \`ai-rules/extensions/\`, not here.`,
    `> Last sync: ${timestamp}`,
    `> Profile: ${profile.project}`,
    ``,
  ].join('\n')

  const body = blocks.map(b => rewritePaths(b, 'codex')).join('\n\n---\n\n')

  return [{
    path: toolConfig.output || 'AGENTS.md',
    content: header + body,
  }]
}

/**
 * Emit `.codex/agents/{name}.md` per agent, frontmatter preserved so Codex
 * can map its native agent config fields. Body paths are rewritten.
 *
 * @param {Array<{ name: string, frontmatter: object, body: string, content: string }>} agents
 */
export function generateAgents(agents, toolConfig, _profile) {
  if (!agents?.length) return []
  if (toolConfig?.agents?.enabled === false) return []
  const outputDir = toolConfig?.agents?.output || '.codex/agents/'
  const normalizedDir = outputDir.replace(/\/?$/, '/')

  return agents.map(a => {
    // Keep original frontmatter + rewritten body. Codex reads the frontmatter
    // fields directly; we do NOT neutralize call sites since Codex supports
    // spawning subagents natively.
    const rewrittenBody = rewritePaths(a.body, 'codex')
    const fmMatch = a.content.match(/^---\r?\n([\s\S]*?)\r?\n---/)
    const frontmatterBlock = fmMatch ? `---\n${fmMatch[1].replace(/\r/g, '')}\n---\n` : ''
    return {
      path: `${normalizedDir}${a.name}.md`,
      content: frontmatterBlock + rewrittenBody,
    }
  })
}
