/**
 * copilot.mjs — GitHub Copilot adapter.
 *
 * Copilot reads `.github/copilot-instructions.md` automatically. It has no
 * native subagent mechanism, so the "agents" concept maps to role prompts.
 *
 * Strategy:
 *   - Rules → `.github/copilot-instructions.md`.
 *   - Agents → one file per agent under `.github/copilot-agents/{name}.md`
 *     (these are NOT auto-loaded by Copilot, but serve as reusable role
 *     prompts the developer can paste / reference). A short index of
 *     available agents is appended to the main instructions file.
 */

import {
  buildMergedAgentsSection,
  neutralizeClaudeDirectives,
  rewritePaths,
} from '../lib/agent-transform.mjs'

export function generate(blocks, toolConfig, profile) {
  const timestamp = new Date().toISOString()
  const header = [
    `# Copilot Instructions — ${profile.project}`,
    ``,
    `<!-- Generated by ai-rules | ${timestamp} | Profile: ${profile.project} -->`,
    `<!-- Edit in ai-rules/core/ or ai-rules/extensions/, not here. -->`,
    ``,
  ].join('\n')

  const body = blocks.map(b => neutralizeClaudeDirectives(rewritePaths(b, 'copilot'))).join('\n\n---\n\n')

  return [{
    path: toolConfig.output || '.github/copilot-instructions.md',
    content: header + body,
  }]
}

/**
 * Emit one role-prompt file per agent plus a merged index.
 */
export function generateAgents(agents, toolConfig, profile) {
  if (!agents?.length) return []
  if (toolConfig?.agents?.enabled === false) return []
  const timestamp = new Date().toISOString()
  const outputDir = toolConfig?.agents?.output || '.github/copilot-agents/'
  const normalizedDir = outputDir.replace(/\/?$/, '/')

  const files = agents.map(a => {
    const desc = String(a.frontmatter?.description || '').replace(/\s+/g, ' ').trim()
    const body = neutralizeClaudeDirectives(rewritePaths(a.body, 'copilot'))
    const header = [
      `# Copilot Role: ${a.name}`,
      `<!-- Generated by ai-rules | ${timestamp} | Profile: ${profile.project} -->`,
      `<!-- Source: core/agents/${a.name}.md -->`,
      desc ? `\n> ${desc}\n` : '',
    ].filter(Boolean).join('\n')
    return {
      path: `${normalizedDir}${a.name}.md`,
      content: header + '\n' + body,
    }
  })

  // Index file bundling all role prompts (helpful for @workspace references).
  const indexContent = [
    `# Copilot Agent Role Index — ${profile.project}`,
    ``,
    `<!-- Generated by ai-rules | ${timestamp} -->`,
    ``,
    `Copilot does not spawn subagents natively; these are role prompts you can attach via`,
    `"Use ${normalizedDir}{name}.md" or paste inline when switching contexts.`,
    ``,
    buildMergedAgentsSection(agents, 'copilot'),
  ].join('\n')

  files.push({
    path: `${normalizedDir}README.md`,
    content: indexContent,
  })

  return files
}
