/**
 * cursor.mjs — Cursor .cursor/rules/*.mdc generation adapter
 */

import {
  neutralizeClaudeDirectives,
  rewritePaths,
  toMdcFrontmatter,
  stringifyFrontmatter,
} from '../lib/agent-transform.mjs'

/**
 * @param {object[]} namedBlocks - Array of [{ name, content }] blocks
 * @param {object} toolConfig - tools.cursor config from profiles/*.yaml
 * @param {object} profile - Full profile object
 * @returns {{ path: string, content: string }[]}
 */
export function generate(namedBlocks, toolConfig, profile) {
  const timestamp = new Date().toISOString()
  const outputDir = toolConfig.output // '.cursor/rules/'

  return namedBlocks.map(({ name, content }) => {
    const mdcHeader = [
      `---`,
      `description: ${getMdcDescription(name)} (auto-generated from ai-rules)`,
      `alwaysApply: true`,
      `---`,
      ``,
      `<!-- Generated by ai-rules | ${timestamp} | Profile: ${profile.project} -->`,
      `<!-- Edit in ai-rules/core/${name}.md or ai-rules/extensions/${name}.md -->`,
      ``,
    ].join('\n')

    return {
      path: `${outputDir}${name}.mdc`,
      content: mdcHeader + content,
    }
  })
}

/**
 * Cursor has no native subagent system, so each core/agents/*.md becomes a
 * use-case-scoped rule at `.cursor/rules/agents/{name}.mdc` (alwaysApply: false).
 * References like "CLAUDE.md" and ".claude/agents/" are rewritten to the
 * Cursor equivalents; Claude-only call sites are neutralized.
 *
 * @param {Array<{ name: string, frontmatter: object, body: string }>} agents
 */
export function generateAgents(agents, toolConfig, profile) {
  if (!agents?.length) return []
  if (toolConfig?.agents?.enabled === false) return []
  const timestamp = new Date().toISOString()
  const outputDir = toolConfig?.agents?.output || '.cursor/rules/agents/'
  const normalizedDir = outputDir.replace(/\/?$/, '/')

  return agents.map(a => {
    const mdcFm = toMdcFrontmatter(a.frontmatter, { tag: 'agent' })
    const body = neutralizeClaudeDirectives(rewritePaths(a.body, 'cursor'))
    const header = [
      `---`,
      stringifyFrontmatter(mdcFm),
      `---`,
      ``,
      `<!-- Generated by ai-rules | ${timestamp} | Profile: ${profile.project} -->`,
      `<!-- Source: core/agents/${a.name}.md — edit there, not here -->`,
      ``,
    ].join('\n')
    return {
      path: `${normalizedDir}${a.name}.mdc`,
      content: header + body,
    }
  })
}

function getMdcDescription(name) {
  const descriptions = {
    '00-identity': 'Persona & Communication',
    '01-git': 'Git Rules',
    '02-code': 'Code Architecture Rules',
    '03-security': 'Security Rules',
    '04-workflow': 'Workflow',
    '05-responses': 'Response Format',
    '06-session': 'Session Management',
  }
  return descriptions[name] || name
}
