/**
 * cursor.mjs — Cursor .cursor/rules/*.mdc generation adapter
 */

/**
 * @param {object[]} namedBlocks - Array of [{ name, content }] blocks
 * @param {object} toolConfig - tools.cursor config from profiles/*.yaml
 * @param {object} profile - Full profile object
 * @returns {{ path: string, content: string }[]}
 */
export function generate(namedBlocks, toolConfig, profile) {
  const timestamp = new Date().toISOString()
  const outputDir = toolConfig.output // '.cursor/rules/'

  return namedBlocks.map(({ name, content }) => {
    const mdcHeader = [
      `---`,
      `description: ${getMdcDescription(name)} (auto-generated from ai-rules)`,
      `alwaysApply: true`,
      `---`,
      ``,
      `<!-- Generated by ai-rules | ${timestamp} | Profile: ${profile.project} -->`,
      `<!-- Edit in ai-rules/core/${name}.md or ai-rules/extensions/${name}.md -->`,
      ``,
    ].join('\n')

    return {
      path: `${outputDir}${name}.mdc`,
      content: mdcHeader + content,
    }
  })
}

function getMdcDescription(name) {
  const descriptions = {
    '00-identity': 'Persona & Communication',
    '01-git': 'Git Rules',
    '02-code': 'Code Architecture Rules',
    '03-security': 'Security Rules',
    '04-workflow': 'Workflow',
    '05-responses': 'Response Format',
    '06-session': 'Session Management',
  }
  return descriptions[name] || name
}
