/**
 * gemini.mjs — Gemini CLI adapter.
 *
 * Gemini reads a single instruction file (`GEMINI.md`) and does not support a
 * native subagent call site. We therefore:
 *   1. Emit rules to GEMINI.md (with path rewriting).
 *   2. Emit per-agent `.gemini/agents/{name}.md` files AND a short
 *      "## Agents" index at the end of GEMINI.md so the user can reference
 *      specific role prompts from the main file.
 */

import {
  neutralizeClaudeDirectives,
  rewritePaths,
} from '../lib/agent-transform.mjs'

export function generate(blocks, toolConfig, profile) {
  const timestamp = new Date().toISOString()
  const header = [
    `# GEMINI.md — ${profile.project}`,
    ``,
    `> ⚠️ Generated by [ai-rules](https://github.com/gencrewai/ai-rules). Edit in \`ai-rules/core/\` or \`ai-rules/extensions/\`, not here.`,
    `> Last sync: ${timestamp}`,
    `> Profile: ${profile.project}`,
    ``,
  ].join('\n')

  const body = blocks.map(b => neutralizeClaudeDirectives(rewritePaths(b, 'gemini'))).join('\n\n---\n\n')

  return [{
    path: toolConfig.output || 'GEMINI.md',
    content: header + body,
  }]
}

export function generateAgents(agents, toolConfig, profile) {
  if (!agents?.length) return []
  if (toolConfig?.agents?.enabled === false) return []
  const timestamp = new Date().toISOString()
  const outputDir = toolConfig?.agents?.output || '.gemini/agents/'
  const normalizedDir = outputDir.replace(/\/?$/, '/')

  return agents.map(a => {
    const desc = String(a.frontmatter?.description || '').replace(/\s+/g, ' ').trim()
    const tools = Array.isArray(a.frontmatter?.tools)
      ? a.frontmatter.tools.join(', ')
      : (a.frontmatter?.tools || '')
    const body = neutralizeClaudeDirectives(rewritePaths(a.body, 'gemini'))
    const header = [
      `# Agent: ${a.name}`,
      `<!-- Generated by ai-rules | ${timestamp} | Profile: ${profile.project} -->`,
      `<!-- Source: core/agents/${a.name}.md — edit there, not here -->`,
      desc ? `\n> ${desc}` : '',
      tools ? `> Allowed tools (reference): ${tools}` : '',
      ``,
    ].filter(Boolean).join('\n')
    return {
      path: `${normalizedDir}${a.name}.md`,
      content: header + '\n' + body,
    }
  })
}
