/**
 * generic.mjs — "Bring your own runner" adapter.
 *
 * Use this when a target tool follows the familiar "instructions file + per-role
 * context files" pattern (Kilo, Augment, Trae, and basically any future runner
 * that doesn't require format-specific magic). It lets you add new tools by
 * writing YAML in a profile instead of a new adapter.
 *
 * Profile example:
 *
 *   tools:
 *     kilo:
 *       adapter: generic
 *       enabled: true
 *       output: .kilo/rules.md
 *       agents: { enabled: true, output: .kilo/agents/ }
 *       # optional — extra path rewrites on top of the built-in CLAUDE.md /
 *       # .claude/agents/ mappings. Keys are RegExp source strings.
 *       path_rewrites:
 *         - { from: "\\bCLAUDE\\.md\\b", to: ".kilo/rules.md" }
 *         - { from: "\\.claude/agents/",  to: ".kilo/agents/" }
 *       # optional — heading used inside role-prompt files
 *       role_heading_prefix: "Kilo Role"
 *
 * Behavior:
 *   - generate()       : concatenates core/extension blocks into `output`,
 *                        applying built-in + custom path rewrites and
 *                        neutralizing Claude-only directives.
 *   - generateAgents() : emits one role-prompt file per agent under
 *                        `agents.output`, same rewriting pipeline.
 */

import { neutralizeClaudeDirectives, rewritePaths } from '../lib/agent-transform.mjs'

function applyCustomRewrites(content, rewrites) {
  if (!Array.isArray(rewrites)) return content
  let out = content
  for (const rule of rewrites) {
    if (!rule?.from) continue
    try {
      const re = new RegExp(rule.from, 'g')
      out = out.replace(re, rule.to ?? '')
    } catch (_) {
      // bad regex — skip silently, adapters should not crash a sync run
    }
  }
  return out
}

function transformForGeneric(content, toolConfig) {
  // No built-in tool key → skip the TOOL_PATH_MAPS pass entirely.
  // Profile owners express their own mappings via `path_rewrites`.
  let out = neutralizeClaudeDirectives(content)
  out = applyCustomRewrites(out, toolConfig.path_rewrites)
  return out
}

export function generate(blocks, toolConfig, profile) {
  if (!toolConfig.output) {
    console.warn(`  ⚠️ generic adapter: tool '${toolConfig._toolName || '?'}' has no 'output' field — skipping rules`)
    return []
  }
  const timestamp = new Date().toISOString()
  const heading = toolConfig.heading || `# ${toolConfig._toolName || 'AI Rules'} — ${profile.project}`
  const header = [
    heading,
    ``,
    `<!-- Generated by ai-rules | ${timestamp} | Profile: ${profile.project} -->`,
    `<!-- Edit in ai-rules/core/ or ai-rules/extensions/, not here. -->`,
    ``,
  ].join('\n')

  const body = blocks.map(b => transformForGeneric(b, toolConfig)).join('\n\n---\n\n')
  return [{ path: toolConfig.output, content: header + body }]
}

export function generateAgents(agents, toolConfig, profile) {
  if (!agents?.length) return []
  if (toolConfig?.agents?.enabled === false) return []
  const outputDir = toolConfig?.agents?.output
  if (!outputDir) {
    console.warn(`  ⚠️ generic adapter: tool '${toolConfig._toolName || '?'}' enabled agents but missing 'agents.output'`)
    return []
  }
  const normalizedDir = outputDir.replace(/\/?$/, '/')
  const timestamp = new Date().toISOString()
  const rolePrefix = toolConfig.role_heading_prefix || `${toolConfig._toolName || 'Agent'} Role`

  return agents.map(a => {
    const desc = String(a.frontmatter?.description || '').replace(/\s+/g, ' ').trim()
    const body = transformForGeneric(a.body, toolConfig)
    const header = [
      `# ${rolePrefix}: ${a.name}`,
      `<!-- Generated by ai-rules | ${timestamp} | Profile: ${profile.project} -->`,
      `<!-- Source: core/agents/${a.name}.md -->`,
      desc ? `\n> ${desc}\n` : '',
    ].filter(Boolean).join('\n')
    return {
      path: `${normalizedDir}${a.name}.md`,
      content: header + '\n' + body,
    }
  })
}
