/**
 * tooling.mjs — Tooling config deployment adapter
 *
 * Reads the `tooling:` block from a profile and generates these project files:
 *   - commitlint.config.mjs     (enforce conventional commits)
 *   - .husky/pre-commit          (run lint-staged)
 *   - .husky/commit-msg          (run commitlint)
 *   - .lintstagedrc.json         (per-stack lint config)
 *   - .claude/hooks/guard-secrets.sh (secret detection)
 *   - .claude/settings.json      (register guard-secrets hook)
 *   - TOOLING_SETUP.md           (npm install instructions)
 *
 * Example profile tooling block:
 *   tooling:
 *     enabled: true
 *     commitlint: true
 *     husky: true
 *     lint_staged: true
 *     secret_scan: true
 *     stack: ts          # ts | py | mixed | docs
 */

import { readFileSync, existsSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')
const TOOLING_DIR = resolve(ROOT, 'templates', 'tooling')
const HOOKS_DIR = resolve(ROOT, 'governance', 'templates', 'hooks')

const LINT_STAGED_MAP = {
  ts: 'lintstagedrc-ts.json',
  py: 'lintstagedrc-py.json',
  mixed: 'lintstagedrc-mixed.json',
}

const DEV_DEPS = {
  commitlint: ['@commitlint/cli', '@commitlint/config-conventional'],
  husky: ['husky'],
  lint_staged_ts: ['lint-staged'],
  lint_staged_py: [],
  lint_staged_mixed: ['lint-staged'],
}

/**
 * @param {object} toolingConfig - tooling block from profile
 * @param {object} profile - Full profile object
 * @returns {{ path: string, content: string, ifNotExists?: boolean, mergeJson?: boolean, executable?: boolean }[]}
 */
export function generate(toolingConfig, profile) {
  if (!toolingConfig?.enabled) return []

  const stack = toolingConfig.stack ?? 'ts'
  const files = []
  const depsToInstall = []

  // 1. commitlint
  if (toolingConfig.commitlint) {
    const src = resolve(TOOLING_DIR, 'commitlint.config.mjs')
    if (existsSync(src)) {
      files.push({
        path: 'commitlint.config.mjs',
        content: readFileSync(src, 'utf-8'),
        ifNotExists: true,
      })
      depsToInstall.push(...DEV_DEPS.commitlint)
    }
  }

  // 2. husky
  if (toolingConfig.husky) {
    const preCommitSrc = resolve(TOOLING_DIR, 'husky', 'pre-commit')
    const commitMsgSrc = resolve(TOOLING_DIR, 'husky', 'commit-msg')

    if (existsSync(preCommitSrc)) {
      files.push({
        path: '.husky/pre-commit',
        content: readFileSync(preCommitSrc, 'utf-8'),
        ifNotExists: true,
        executable: true,
      })
    }
    if (existsSync(commitMsgSrc)) {
      files.push({
        path: '.husky/commit-msg',
        content: readFileSync(commitMsgSrc, 'utf-8'),
        ifNotExists: true,
        executable: true,
      })
    }
    depsToInstall.push(...DEV_DEPS.husky)
  }

  // 3. lint-staged
  if (toolingConfig.lint_staged && stack !== 'docs') {
    const lintStagedFile = LINT_STAGED_MAP[stack]
    if (lintStagedFile) {
      const src = resolve(TOOLING_DIR, lintStagedFile)
      if (existsSync(src)) {
        files.push({
          path: '.lintstagedrc.json',
          content: readFileSync(src, 'utf-8'),
          ifNotExists: true,
        })
        const depsKey = `lint_staged_${stack}`
        depsToInstall.push(...(DEV_DEPS[depsKey] || DEV_DEPS.lint_staged_ts))
      }
    }
  }

  // 4. guard-secrets.sh (Claude hook)
  if (toolingConfig.secret_scan) {
    const hookSrc = resolve(HOOKS_DIR, 'guard-secrets.sh')
    if (existsSync(hookSrc)) {
      files.push({
        path: '.claude/hooks/guard-secrets.sh',
        content: readFileSync(hookSrc, 'utf-8'),
        executable: true,
      })
    }

    // Register hook in settings.json
    files.push({
      path: '.claude/settings.json',
      content: buildSettingsJson(),
      mergeJson: true,
    })
  }

  // 5. TOOLING_SETUP.md — npm install instructions
  const setupContent = buildSetupMd(toolingConfig, stack, depsToInstall, profile)
  files.push({
    path: 'TOOLING_SETUP.md',
    content: setupContent,
  })

  return files
}

/**
 * Generate settings.json to register guard-secrets hook
 */
function buildSettingsJson() {
  const settings = {
    hooks: {
      PreToolUse: [
        {
          matcher: 'Bash',
          hooks: [
            {
              type: 'command',
              command: 'bash .claude/hooks/guard-secrets.sh',
            },
          ],
        },
      ],
    },
  }
  return JSON.stringify(settings, null, 2) + '\n'
}

/**
 * Generate TOOLING_SETUP.md — guide for items requiring manual installation
 */
function buildSetupMd(toolingConfig, stack, depsToInstall, profile) {
  const lines = [
    `# Tooling Setup — ${profile.project}`,
    '',
    `> Generated by [ai-rules](https://github.com/gencrewai/ai-rules) tooling adapter.`,
    `> Last sync: ${new Date().toISOString()}`,
    '',
  ]

  // npm dependency installation
  const uniqueDeps = [...new Set(depsToInstall)]
  if (uniqueDeps.length > 0) {
    lines.push('## 1. Install Dependencies', '')
    lines.push('```bash')
    lines.push(`npm install --save-dev ${uniqueDeps.join(' ')}`)
    lines.push('```', '')
  }

  // Husky initialization
  if (toolingConfig.husky) {
    lines.push('## 2. Initialize Husky', '')
    lines.push('```bash')
    lines.push('npx husky init')
    lines.push('```', '')
    lines.push('> `.husky/pre-commit` and `.husky/commit-msg` are already generated.', '')
  }

  // GitHub Branch Protection guide
  lines.push('## 3. GitHub Branch Protection (manual setup required)', '')
  lines.push('GitHub repository Settings → Branches → Branch protection rules:', '')
  lines.push('- [ ] `main` / `master` Add protection rule for branch')
  lines.push('- [ ] "Require a pull request before merging" Enable')
  lines.push('- [ ] "Require status checks to pass before merging" Enable')
  lines.push('- [ ] "Do not allow force pushes" Enable')
  lines.push('')

  // ESLint no-console (manual)
  if (stack === 'ts' || stack === 'mixed') {
    lines.push('## 4. ESLint no-console Rule (manual addition)', '')
    lines.push('Add the following rule to your ESLint config:', '')
    lines.push('```json')
    lines.push('{')
    lines.push('  "rules": {')
    lines.push('    "no-console": ["warn", { "allow": ["error"] }]')
    lines.push('  }')
    lines.push('}')
    lines.push('```', '')
  }

  // Python ruff (manual)
  if (stack === 'py' || stack === 'mixed') {
    lines.push('## 4. Verify Ruff Configuration', '')
    lines.push('Check that ruff is configured in `pyproject.toml` or `ruff.toml`.', '')
  }

  lines.push('---', '')
  lines.push('You may delete this file after completing the above items.', '')

  return lines.join('\n')
}
