/**
 * windsurf.mjs — Windsurf .windsurfrules generation adapter
 * Concat all blocks into a single file
 */

import { neutralizeClaudeDirectives, rewritePaths } from '../lib/agent-transform.mjs'

export function generate(blocks, toolConfig, profile) {
  const timestamp = new Date().toISOString()
  const header = [
    `# .windsurfrules`,
    `# Generated by ai-rules | ${timestamp} | Profile: ${profile.project}`,
    `# Edit in https://github.com/gencrewai/ai-rules`,
    ``,
  ].join('\n')

  return [{
    path: toolConfig.output,
    content: header + blocks.join('\n\n---\n\n'),
  }]
}

/**
 * Windsurf has no native subagent system. Each agent is emitted as a rule file
 * under `.windsurf/rules/agents/{name}.md` with paths rewritten to Windsurf
 * equivalents. Call-site directives that only make sense for Claude are
 * neutralized to plain role guidance.
 */
export function generateAgents(agents, toolConfig, profile) {
  if (!agents?.length) return []
  if (toolConfig?.agents?.enabled === false) return []
  const timestamp = new Date().toISOString()
  const outputDir = toolConfig?.agents?.output || '.windsurf/rules/agents/'
  const normalizedDir = outputDir.replace(/\/?$/, '/')

  return agents.map(a => {
    const desc = String(a.frontmatter?.description || '').replace(/\s+/g, ' ').trim()
    const body = neutralizeClaudeDirectives(rewritePaths(a.body, 'windsurf'))
    const header = [
      `# Agent: ${a.name}`,
      `<!-- Generated by ai-rules | ${timestamp} | Profile: ${profile.project} -->`,
      `<!-- Source: core/agents/${a.name}.md — edit there, not here -->`,
      desc ? `\n> ${desc}\n` : '',
    ].join('\n')
    return {
      path: `${normalizedDir}${a.name}.md`,
      content: header + '\n' + body,
    }
  })
}
