/**
 * windsurf.mjs — Windsurf .windsurfrules generation adapter
 * Concat all blocks into a single file
 */

export function generate(blocks, toolConfig, profile) {
  const timestamp = new Date().toISOString()
  const header = [
    `# .windsurfrules`,
    `# Generated by ai-rules | ${timestamp} | Profile: ${profile.project}`,
    `# Edit in https://github.com/gencrewai/ai-rules`,
    ``,
  ].join('\n')

  return [{
    path: toolConfig.output,
    content: header + blocks.join('\n\n---\n\n'),
  }]
}
