#!/usr/bin/env node
/**
 * onboard.mjs — Interactive CLI for new project onboarding
 *
 * Usage: node scripts/onboard.mjs
 *
 * 3 steps, ~3 minutes:
 *   1. Enter project info
 *   2. Auto-generate profiles/{name}.yaml
 *   3. Instructions to run node sync.mjs --apply --project {name}
 */

import { createInterface } from 'readline'
import { writeFileSync, existsSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')

const rl = createInterface({ input: process.stdin, output: process.stdout })
const ask = (q) => new Promise(resolve => rl.question(q, resolve))

console.log('\n🚀 ai-rules New Project Onboarding\n')
console.log('3 steps, ~3 minutes\n')

try {
  // Step 1: Basic info
  const name = await ask('1. Project name (e.g., my-project): ')
  const targetPath = await ask('2. Local path (e.g., /path/to/projects/my-project): ')
  const githubRepo = await ask('3. GitHub repo (e.g., your-org/my-project, press Enter to skip): ')

  // Step 2: Tool selection
  console.log('\n4. AI tools to use (y/n):')
  const useClaude = (await ask('   Claude Code (CLAUDE.md)? [Y/n]: ')).toLowerCase() !== 'n'
  const useCursor = (await ask('   Cursor (.cursor/rules/)? [y/N]: ')).toLowerCase() === 'y'
  const useWindsurf = (await ask('   Windsurf/other (.windsurfrules)? [y/N]: ')).toLowerCase() === 'y'

  // Step 3: Base profile
  console.log('\n5. Base profile:')
  console.log('   a) _default (basic rules only)')
  console.log('   b) my-saas-app (MyApp full rules — production service)')
  console.log('   c) Custom setup')
  const base = await ask('   Choose [a/b/c]: ')

  let coreBlocks, extensions
  if (base === 'b') {
    coreBlocks = ['00-identity', '01-git', '02-code', '03-security', '04-workflow', '05-responses', '06-session']
    extensions = ['my-saas-app-agents', 'my-saas-app-ci']
  } else {
    coreBlocks = ['01-git', '02-code', '03-security', '04-workflow', '06-session']
    extensions = []
  }

  // Generate yaml
  const yaml = [
    `# ${name}.yaml — ${name} profile`,
    `# Generated by onboard.mjs`,
    ``,
    `project: ${name}`,
    `target_path: ${targetPath}`,
    `github_repo: ${githubRepo || ''}`,
    ``,
    `tools:`,
    `  claude-code:`,
    `    enabled: ${useClaude}`,
    `    output: CLAUDE.md`,
    `  cursor:`,
    `    enabled: ${useCursor}`,
    `    output: .cursor/rules/`,
    `  windsurf:`,
    `    enabled: ${useWindsurf}`,
    `    output: .windsurfrules`,
    `  plain:`,
    `    enabled: true`,
    `    output: AI-RULES.md`,
    ``,
    `core:`,
    ...coreBlocks.map(b => `  - ${b}`),
    ``,
    `extensions:`,
    ...extensions.map(e => `  - ${e}`),
    ``,
    `docs:`,
    `  - checklist/project-kickoff`,
    `  - checklist/ai-logs`,
    ``,
    `overrides: {}`,
  ].join('\n')

  const outputPath = join(ROOT, 'profiles', `${name}.yaml`)
  if (existsSync(outputPath)) {
    const overwrite = await ask(`\n⚠️  ${outputPath} already exists. Overwrite? [y/N]: `)
    if (overwrite.toLowerCase() !== 'y') {
      console.log('Cancelled.')
      process.exit(0)
    }
  }

  writeFileSync(outputPath, yaml, 'utf-8')

  console.log(`\n✅ Profile created: profiles/${name}.yaml`)
  console.log('\nNext steps:')
  console.log(`  1. Review/edit profiles/${name}.yaml (if needed)`)
  console.log(`  2. Apply: node scripts/sync.mjs --apply --project ${name}`)
  console.log(`  3. Validate: node scripts/validate.mjs`)

} finally {
  rl.close()
}
